config/routes.rb
Portal::Application.routes.draw do


  resources :access_levels
  resources :access_groups
  resources :audits
  resources :calls
  resources :call_locations
  resources :call_types
  resources :contact_types
  resources :contacts
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_assignments
  resources :device_batteries
  resources :device_carriers
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :user_locations


#######################################
##  todo fix to direct to appropriate 
##  place based on login creds
#######################################

  authenticated :user do
    root :to => "dashboard#index"
  end

#######################################


  devise_for :users
  resources :users

  root :to => "dashboard#index"

#######################################
##  redirect for calltracker
##  to be replaced with dynamic dash 
#######################################

  match "/dashboard" => "dashboard#index"

#######################################

  # custom admin routes
  get "callsadmin" => "calls#admin", :as => "callsadmin"

  # get routes for reports
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "reports/rma_devices" => "reports#rma_devices", :as => "rma_devices"
  get "reports/onsite_devices" => "reports#onsite_devices", :as => "onsite_devices"
  get "reports/unreturned_devices" => "reports#unreturned_devices", :as => "unreturned_devices"
  get "reports/full_inventory" => "reports#full_inventory", :as => "full_inventory"
  get "reports/last_known_location" => "reports#last_known_location", :as => "last_known_location"

  # get routes for authentication
  get "users/signup" => "home#index"
  get "searches/results" => "searches#results", :as => "searches"
  get "/search" => "searches#index", :as => "search"

  # post routes for search
  post "searches/patient" => "searches#patient", :as => "patientsearch"
  post "searches/type" => "searches#type", :as => "typesearch"
  post "searches/rep" => "searches#rep", :as => "repsearch"
  post "searches/date" => "searches#date", :as => "datesearch"
  post "searches/device" => "searches#device", :as => "devicesearch"
  post "searches/assignment_device" => "searches#assignment_device", :as => "assignment_device_search"
  post "searches/assignment_patient" => "searches#assignment_patient", :as => "assignment_patient_search"
  post "searches/assignment_location" => "searches#assignment_location", :as => "assignment_location_search"


end

app/models/access_level.rb
class AccessLevel < ActiveRecord::Base
end

app/controllers/access_levels_controller.rb
class AccessLevelsController < ApplicationController
  # GET /access_levels
  # GET /access_levels.json
  def index
    @access_levels = AccessLevel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @access_levels }
    end
  end

  # GET /access_levels/1
  # GET /access_levels/1.json
  def show
    @access_level = AccessLevel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @access_level }
    end
  end

  # GET /access_levels/new
  # GET /access_levels/new.json
  def new
    @access_level = AccessLevel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @access_level }
    end
  end

  # GET /access_levels/1/edit
  def edit
    @access_level = AccessLevel.find(params[:id])
  end

  # POST /access_levels
  # POST /access_levels.json
  def create
    @access_level = AccessLevel.new(params[:access_level])

    respond_to do |format|
      if @access_level.save
        format.html { redirect_to @access_level, notice: 'Access level was successfully created.' }
        format.json { render json: @access_level, status: :created, location: @access_level }
      else
        format.html { render action: "new" }
        format.json { render json: @access_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /access_levels/1
  # PUT /access_levels/1.json
  def update
    @access_level = AccessLevel.find(params[:id])

    respond_to do |format|
      if @access_level.update_attributes(params[:access_level])
        format.html { redirect_to @access_level, notice: 'Access level was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @access_level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /access_levels/1
  # DELETE /access_levels/1.json
  def destroy
    @access_level = AccessLevel.find(params[:id])
    @access_level.destroy

    respond_to do |format|
      format.html { redirect_to access_levels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/access_levels_helper.rb
module AccessLevelsHelper
end

app/views/access_levels/_form.html.erb
<%= form_for(@access_level) do |f| %>
  <% if @access_level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@access_level.errors.count, "error") %> prohibited this access_level from being saved:</h2>

      <ul>
      <% @access_level.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/access_levels/edit.html.erb
<h1>Editing access_level</h1>

<%= render 'form' %>

<%= link_to 'Show', @access_level %> |
<%= link_to 'Back', access_levels_path %>

app/views/access_levels/index.html.erb
<h1>Listing access_levels</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @access_levels.each do |access_level| %>
  <tr>
    <td><%= link_to 'Show', access_level %></td>
    <td><%= link_to 'Edit', edit_access_level_path(access_level) %></td>
    <td><%= link_to 'Destroy', access_level, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Access level', new_access_level_path %>

app/views/access_levels/new.html.erb
<h1>New access_level</h1>

<%= render 'form' %>

<%= link_to 'Back', access_levels_path %>

app/views/access_levels/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_access_level_path(@access_level) %> |
<%= link_to 'Back', access_levels_path %>