config/routes.rb
Portal::Application.routes.draw do


  resources :access_levels
  resources :access_groups
  resources :audits
  resources :calls
  resources :call_locations
  resources :call_types
  resources :contact_types
  resources :contacts
  resources :disposable_types
  resources :disposables
  resources :devices
  resources :device_assignments
  resources :device_batteries
  resources :device_carriers
  resources :device_problem_statuses
  resources :device_problems
  resources :device_tests
  resources :device_types
  resources :device_statuses
  resources :groups
  resources :locations
  resources :location_assignments
  resources :location_types
  resources :patients
  resources :patient_assignments
  resources :practices
  resources :user_locations


#######################################
##  todo fix to direct to appropriate 
##  place based on login creds
#######################################

  authenticated :user do
    root :to => "dashboard#index"
  end

#######################################


  devise_for :users
  resources :users

  root :to => "dashboard#index"

#######################################
##  redirect for calltracker
##  to be replaced with dynamic dash 
#######################################

  match "/dashboard" => "dashboard#index"

#######################################

  # custom admin routes
  get "callsadmin" => "calls#admin", :as => "callsadmin"

  # get routes for reports
  get "reports/all_locations_summary" => "reports#all_locations_summary", :as => "all_locations_summary"
  get "reports/location_summary/:id" => "reports#location_summary", :as => "location_summary"
  get "reports/problematic_devices" => "reports#problematic_devices", :as => "problematic_devices"
  get "reports/devices_in_use" => "reports#devices_in_use", :as => "devices_in_use"
  get "reports/rma_devices" => "reports#rma_devices", :as => "rma_devices"
  get "reports/onsite_devices" => "reports#onsite_devices", :as => "onsite_devices"
  get "reports/unreturned_devices" => "reports#unreturned_devices", :as => "unreturned_devices"
  get "reports/full_inventory" => "reports#full_inventory", :as => "full_inventory"
  get "reports/last_known_location" => "reports#last_known_location", :as => "last_known_location"

  # get routes for authentication
  get "users/signup" => "home#index"
  get "searches/results" => "searches#results", :as => "searches"
  get "/search" => "searches#index", :as => "search"

  # post routes for search
  post "searches/patient" => "searches#patient", :as => "patientsearch"
  post "searches/type" => "searches#type", :as => "typesearch"
  post "searches/rep" => "searches#rep", :as => "repsearch"
  post "searches/date" => "searches#date", :as => "datesearch"
  post "searches/device" => "searches#device", :as => "devicesearch"
  post "searches/assignment_device" => "searches#assignment_device", :as => "assignment_device_search"
  post "searches/assignment_patient" => "searches#assignment_patient", :as => "assignment_patient_search"
  post "searches/assignment_location" => "searches#assignment_location", :as => "assignment_location_search"


end

app/models/call_location.rb
class CallLocation < ActiveRecord::Base

  has_many :calls

end

app/controllers/call_locations_controller.rb
class CallLocationsController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /call_locations
  # GET /call_locations.json
  def index
    @call_locations = CallLocation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @call_locations }
    end
  end

  # GET /call_locations/1
  # GET /call_locations/1.json
  def show
    @call_location = CallLocation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @call_location }
    end
  end

  # GET /call_locations/new
  # GET /call_locations/new.json
  def new
    @call_location = CallLocation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @call_location }
    end
  end

  # GET /call_locations/1/edit
  def edit
    @call_location = CallLocation.find(params[:id])
  end

  # POST /call_locations
  # POST /call_locations.json
  def create
    @call_location = CallLocation.new(params[:call_location])

    respond_to do |format|
      if @call_location.save
        format.html { redirect_to @call_location, notice: 'Call location was successfully created.' }
        format.json { render json: @call_location, status: :created, location: @call_location }
      else
        format.html { render action: "new" }
        format.json { render json: @call_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /call_locations/1
  # PUT /call_locations/1.json
  def update
    @call_location = CallLocation.find(params[:id])

    respond_to do |format|
      if @call_location.update_attributes(params[:call_location])
        format.html { redirect_to @call_location, notice: 'Call location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @call_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /call_locations/1
  # DELETE /call_locations/1.json
  def destroy
    @call_location = CallLocation.find(params[:id])
    @call_location.destroy

    respond_to do |format|
      format.html { redirect_to call_locations_url }
      format.json { head :no_content }
    end
  end
end

app/views/call_locations/_form.html.erb
<%= form_for(@call_location) do |f| %>
  <% if @call_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@call_location.errors.count, "error") %> prohibited this call_location from being saved:</h2>

      <ul>
      <% @call_location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :call_location %><br />
    <%= f.text_field :call_location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/call_locations/edit.html.erb
<h1>Editing call_location</h1>

<%= render 'form' %>

<%= link_to 'Show', @call_location %> |
<%= link_to 'Back', call_locations_path %>

app/views/call_locations/index.html.erb
<h1>Listing call_locations</h1>

<table>
  <tr>
    <th>Call location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @call_locations.each do |call_location| %>
  <tr>
    <td><%= call_location.call_location %></td>
    <td><%= link_to 'Show', call_location %></td>
    <td><%= link_to 'Edit', edit_call_location_path(call_location) %></td>
    <td><%= link_to 'Destroy', call_location, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Call location', new_call_location_path %>

app/views/call_locations/new.html.erb
<h1>New call_location</h1>

<%= render 'form' %>

<%= link_to 'Back', call_locations_path %>

app/views/call_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Call location:</b>
  <%= @call_location.call_location %>
</p>


<%= link_to 'Edit', edit_call_location_path(@call_location) %> |
<%= link_to 'Back', call_locations_path %>